### PR TITLE
docs: updating route handler file convention

### PR DESCRIPTION
**Pull request by DarrylBrooks97**
Updating the file syntax to match NextJS's [file convention](https://nextjs.org/docs/app/building-your-application/routing/route-handlers)

### CODE REVIEW

**Review by alexisintech — APPROVED** [review]
Good catch! 😸💖

**Review by royanger — APPROVED** [review]
This is good. I would suggest just using .ts and not even including .js anymore. That's become our general convention.

**Comment by alexisintech** [comment]
> This is good. I would suggest just using .ts and not even including .js anymore. That's become our general convention.

Agreed! @DarrylBrooks97 could you please remove the js file extension, and simply have the .ts or .tsx extension?

This PR can be merged once that is done :)

**Comment by DarrylBrooks97** [comment]
Perfect! Thank y'all, I'm loving the product btw it's good to see full TS support 🎉

**Comment by alexisintech** [comment]
Thanks so much for contributing 😸💖

**Pull request merged**
