### PR TITLE
Relocate NextJS' clerkClient documentation to its own page

### PR DESCRIPTION
**Pull request by SuperLanceur**
I find it confusing that this part of the documentation is under the Route Handlers page. I think it should be easier to find.

### CODE REVIEW

**Comment by royanger** [comment]
/docs/references/backend/overview is already a full reference for clerkClient. The section edited here should, in my opinion, remain in its current place and a link or callout should be added pointing to the /docs/references/backend/overview doc. Added [PR-323](https://github.com/clerkinc/clerk-docs/pull/323) to this affect @alexisintech

**Comment by alexisintech** [comment]
In relation to this, we can expand on how to access the backend SDK's on the backend reference overview.
https://github.com/clerkinc/clerk-docs/pull/324

**Comment by royanger** [comment]
> In relation to this, we can expand on how to access the backend SDK's on the backend reference overview. #324

You mean in /docs/references/backend/overview ? I can add that to my PR later today if so.

**Comment by alexisintech** [comment]
Solved with [PR-323](https://github.com/clerkinc/clerk-docs/pull/323) and [PR-324](https://github.com/clerkinc/clerk-docs/pull/324)

**Pull request closed without merging**
